# Generated by Django 4.0.5 on 2022-07-06 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('comapany_name', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('website', models.CharField(default='', max_length=150)),
                ('description', models.CharField(default='', max_length=700)),
                ('logo_pic', models.ImageField(upload_to='app/img/company')),
            ],
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('is_active', models.CharField(default='True', max_length=250)),
                ('is_verified', models.CharField(default='False', max_length=250)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=300)),
                ('companyname', models.CharField(max_length=300)),
                ('companyaddress', models.CharField(max_length=300)),
                ('jobdescription', models.TextField(max_length=700)),
                ('qualification', models.CharField(max_length=300)),
                ('resposibilities', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('companywebsite', models.CharField(max_length=300)),
                ('companyemail', models.CharField(max_length=300)),
                ('companycontact', models.CharField(max_length=300)),
                ('salarypackage', models.CharField(max_length=300)),
                ('experience', models.CharField(max_length=50)),
                ('job_type', models.CharField(default='', max_length=150)),
                ('logo', models.ImageField(default='', upload_to='app/img/jobpost')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermaster'),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('min_salary', models.CharField(default='', max_length=50)),
                ('max_salary', models.CharField(default='', max_length=50)),
                ('job_type', models.CharField(max_length=150)),
                ('job_category', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('highestedu', models.CharField(max_length=150)),
                ('experience', models.CharField(max_length=150)),
                ('website', models.CharField(max_length=150)),
                ('shift', models.CharField(max_length=150)),
                ('jobdescription', models.CharField(max_length=150)),
                ('profile_pic', models.ImageField(upload_to='app/img/candidate')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='Applyjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=300)),
                ('experience', models.CharField(max_length=250)),
                ('website', models.CharField(max_length=250)),
                ('min_salary', models.CharField(max_length=250)),
                ('max_salary', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('resume', models.FileField(upload_to='app/resume')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobdetails')),
            ],
        ),
    ]
