# Generated by Django 4.0.5 on 2022-07-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='comdetaile',
            field=models.CharField(default='', max_length=700),
        ),
    ]
